#version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-spring
    restart: always
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: petros
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
